[project]
name = "pie"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mypy>=1.15.0",
    "pydantic>=2.10.6",
    "ruff>=0.11.0",
]
